name: ci

on:
    push:
    pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version:
          - "3.10"

    name: Test
    runs-on: ${{ matrix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          git clone https://github.com/wagesreiterb/lazySSH/
          pip install -r ./lazySSH/requirements.txt
          cd ./lazySSH/
          python3 ./main.py &
          # sleep 10s
          # echo "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
          # ps -ef | grep python

      - name: Test with unittest
        run: |
          # echo "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
          # ps -ef | grep python
          # ls -l /home/runner/work/cmg_health_checks/cmg_health_checks/cfg/tests_dev.yaml
          # netstat -aon
          # sudo iptables -S
          # sudo ifconfig -a
          # echo "1111"
          # ssh -v -tt cmg@127.0.0.1 -p 2222
          echo "2222"
          pip install keyring
          pip install pytz
          pip install keyrings.alt
          python -c "import keyring; keyring.set_password(service_name='CMGDev', username='cmg', password='cmg')"
          python -c "import keyring; kr=keyring.get_credential(service_name='CMGDev'); print(kr.username); print(kr.password)"
          python3 -m unittest discover -s ./test  -p 'test_*.py'
          echo "3333"
